### ISSUE TITLE
有没有ALSO的使用教程

### ISSUE THREAD

**Issue by GitZgl** [nbulsi/also#25]
褚老师，
您好，我最近正在关注您的综合工具ALSO，想拿安装下这个工具实际跑一个电路的综合，但是没有看到相关的使用教程？想问下有简单的使用说明吗？工具里面包含哪些命令？每个命令如何使用？
还有2个问题：1、ALSO目前支持ASIC的综合吗？之前工艺库的mapping吗？2、ALSO里面有没有使用中间表达语言？比如yosys的RTLIL这种。

**Comment by xCodeleaner** [comment]
储

**Comment by zfchu** [comment]
Communicated offline. Thus close the issue.
